services:
  app:
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/demo-with-docker
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mysqlserver
    networks:
      - mynetwork

  mysqlserver:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=anhtuan1206
      - MYSQL_PASSWORD=anhtuan1206
      - MYSQL_DATABASE=demo-with-docker
    volumes:
      - mysql_data_demo:/var/lib/mysql_data_demo
    networks:
      - mynetwork
volumes:
  mysql_data_demo:
networks:
  mynetwork: